# Generated by Django 5.1.1 on 2024-09-12 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='NovelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='NovelCompletionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='NovelLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='NovelTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('summary', models.TextField(max_length=16256)),
                ('number_of_chapters', models.IntegerField()),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='novel', to='links_manager.novellink')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novels', to='novels_storage.novelauthor')),
                ('categories', models.ManyToManyField(related_name='novels', to='novels_storage.novelcategory')),
                ('completion_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novels', to='novels_storage.novelcompletionstatus')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novels', to='novels_storage.novellanguage')),
                ('tags', models.ManyToManyField(related_name='novels', to='novels_storage.noveltag')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateField()),
                ('name', models.CharField(max_length=512)),
                ('text', models.TextField(max_length=32512)),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='chapter', to='links_manager.chapterlink')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='novels_storage.novel')),
            ],
        ),
    ]
