# Generated by Django 5.1.1 on 2024-09-13 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels_storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='date_uploaded',
            new_name='date_published',
        ),
    ]
