# Generated by Django 5.1.1 on 2024-09-14 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels_storage', '0002_rename_date_uploaded_chapter_date_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='number_of_chapters',
        ),
        migrations.AlterField(
            model_name='novel',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novels', to='novels_storage.novellanguage'),
        ),
    ]
