# Generated by Django 5.1.1 on 2024-09-14 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_manager', '0006_remove_website_novel_pages_directory'),
        ('novels_storage', '0003_remove_novel_number_of_chapters_alter_novel_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='links_manager.chapterlink'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novels', to='novels_storage.novelauthor'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='completion_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novels', to='novels_storage.novelcompletionstatus'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novels', to='novels_storage.novellanguage'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='novel', to='links_manager.novellink'),
        ),
    ]
