# Generated by Django 5.1.1 on 2024-09-15 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels_storage', '0005_chapter_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('website_directory', models.CharField(blank=True, max_length=2048, null=True)),
                ('novel_link_pages_directory', models.CharField(blank=True, max_length=8096, null=True)),
                ('novels_directory', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='link',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='link',
        ),
        migrations.AddField(
            model_name='novel',
            name='chapter_link_pages_directory',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='novel',
            name='chapter_pages_directory',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='novel',
            name='novel_directory',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='novel',
            name='website',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='novels', to='novels_storage.website'),
            preserve_default=False,
        ),
    ]
