# Generated by Django 5.1.1 on 2024-09-16 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels_storage', '0006_website_remove_chapter_link_remove_novel_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='initialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='novel',
            name='is_being_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='novel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novels', to='novels_storage.novelauthor'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='completion_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novels', to='novels_storage.novelcompletionstatus'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novels', to='novels_storage.novellanguage'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='summary',
            field=models.TextField(blank=True, max_length=16256, null=True),
        ),
    ]
