# Generated by Django 5.1.1 on 2024-09-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('t_start', models.DateTimeField(auto_now=True)),
                ('t_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
