# Generated by Django 5.1.1 on 2024-09-12 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiders_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpiderProcess',
            new_name='ScraperInstance',
        ),
    ]
