# Generated by Django 5.1.1 on 2024-09-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders_manager', '0002_rename_spiderprocess_scraperinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processes_alive', models.IntegerField(default=0)),
                ('processes_done', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='ScraperInstance',
        ),
    ]
