# Generated by Django 5.1.1 on 2024-09-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders_manager', '0003_update_delete_scraperinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=8096)),
                ('maximum_grace_period', models.IntegerField(default=5)),
                ('current_grace_period', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Update',
        ),
    ]
