# Generated by Django 5.1.1 on 2024-09-13 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_manager', '0006_remove_website_novel_pages_directory'),
        ('spiders_manager', '0005_spiderinstanceprocess_updatecycle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatecycle',
            name='processes_idle',
        ),
        migrations.RemoveField(
            model_name='websiteupdateinstance',
            name='processes_idle',
        ),
        migrations.AlterField(
            model_name='spiderinstanceprocess',
            name='maximum_grace_period',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='websiteupdateinstance',
            name='update_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_update_instances', to='spiders_manager.updatecycle'),
        ),
        migrations.AlterField(
            model_name='websiteupdateinstance',
            name='website',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='update_instance', to='links_manager.website'),
        ),
    ]
