# Generated by Django 5.1.1 on 2024-09-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders_manager', '0006_remove_updatecycle_processes_idle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderinstanceprocess',
            name='exception_message',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
