# Generated by Django 5.1.1 on 2024-09-13 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_manager', '0006_remove_website_novel_pages_directory'),
        ('spiders_manager', '0007_spiderinstanceprocess_exception_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteupdateinstance',
            name='website',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='update_instance', to='links_manager.website'),
        ),
    ]
