# Generated by Django 5.1.1 on 2024-09-15 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiders_manager', '0008_alter_websiteupdateinstance_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteupdateinstance',
            name='update_cycle',
        ),
        migrations.RemoveField(
            model_name='websiteupdateinstance',
            name='website',
        ),
        migrations.DeleteModel(
            name='SpiderInstanceProcess',
        ),
        migrations.DeleteModel(
            name='UpdateCycle',
        ),
        migrations.DeleteModel(
            name='WebsiteUpdateInstance',
        ),
    ]
