# Generated by Django 5.1.1 on 2024-09-15 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novels_storage', '0006_website_remove_chapter_link_remove_novel_link_and_more'),
        ('spiders_manager', '0009_remove_websiteupdateinstance_update_cycle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_processes_per_site', models.IntegerField()),
                ('t_start', models.DateTimeField(auto_now=True)),
                ('db_processes_idle', models.IntegerField(default=0)),
                ('db_processes_in_progress', models.IntegerField(default=0)),
                ('db_processes_scraper_error', models.IntegerField(default=0)),
                ('db_processes_processor_error', models.IntegerField(default=0)),
                ('db_processes_launch_error', models.IntegerField(default=0)),
                ('db_processes_finished', models.IntegerField(default=0)),
                ('db_novel_links', models.IntegerField(default=0)),
                ('db_chapter_links', models.IntegerField(default=0)),
                ('db_novels', models.IntegerField(default=0)),
                ('db_chapters', models.IntegerField(default=0)),
                ('db_unmatched_novel_links', models.IntegerField(default=0)),
                ('db_existing_novels_updated', models.IntegerField(default=0)),
                ('db_new_novel_links_added', models.IntegerField(default=0)),
                ('db_new_chapter_links_added', models.IntegerField(default=0)),
                ('db_new_novels_added', models.IntegerField(default=0)),
                ('db_new_chapters_added', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteUpdateInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_processes', models.IntegerField()),
                ('t_start', models.DateTimeField(auto_now=True)),
                ('site_processes_idle', models.IntegerField(default=0)),
                ('site_processes_in_progress', models.IntegerField(default=0)),
                ('site_processes_scraper_error', models.IntegerField(default=0)),
                ('site_processes_processor_error', models.IntegerField(default=0)),
                ('site_processes_launch_error', models.IntegerField(default=0)),
                ('site_processes_finished', models.IntegerField(default=0)),
                ('site_novel_links', models.IntegerField(default=0)),
                ('site_chapter_links', models.IntegerField(default=0)),
                ('site_novels', models.IntegerField(default=0)),
                ('site_chapters', models.IntegerField(default=0)),
                ('site_existing_novels_updated', models.IntegerField(default=0)),
                ('site_unmatched_novel_links', models.IntegerField(default=0)),
                ('site_new_novel_links_added', models.IntegerField(default=0)),
                ('site_new_chapter_links_added', models.IntegerField(default=0)),
                ('site_new_novels_added', models.IntegerField(default=0)),
                ('site_new_chapters_added', models.IntegerField(default=0)),
                ('update_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_update_instances', to='spiders_manager.updatecycle')),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='update_instance', to='novels_storage.website')),
            ],
        ),
        migrations.CreateModel(
            name='SpiderInstanceProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=8096)),
                ('state', models.CharField(default='idle', max_length=64)),
                ('maximum_scraper_grace_period', models.IntegerField(default=1)),
                ('current_scraper_grace_period', models.IntegerField(default=0)),
                ('maximum_processor_retry_unverified_content_count', models.IntegerField(default=1)),
                ('current_processor_retry_unverified_content_count', models.IntegerField(default=0)),
                ('bad_content_page_paths', models.CharField(blank=True, max_length=32128, null=True)),
                ('exception_message', models.CharField(blank=True, max_length=4096, null=True)),
                ('website_update_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spider_processes', to='spiders_manager.websiteupdateinstance')),
            ],
        ),
    ]
