# Generated by Django 5.1.1 on 2024-09-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders_manager', '0010_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spiderinstanceprocess',
            old_name='current_processor_retry_unverified_content_count',
            new_name='current_processor_retry_on_bad_content',
        ),
        migrations.RenameField(
            model_name='spiderinstanceprocess',
            old_name='maximum_processor_retry_unverified_content_count',
            new_name='max_processor_retry_on_bad_content',
        ),
        migrations.AddField(
            model_name='websiteupdateinstance',
            name='critical_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='websiteupdateinstance',
            name='critical_error_message',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
