# Generated by Django 5.1.1 on 2024-09-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders_manager', '0011_rename_current_processor_retry_unverified_content_count_spiderinstanceprocess_current_processor_retr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiderinstanceprocess',
            name='max_processor_retry_on_bad_content',
            field=models.IntegerField(default=5),
        ),
    ]
