# Generated by Django 5.1.1 on 2024-09-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders_manager', '0013_rename_db_chapter_links_updatecycle_chapter_link_pages_processed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websiteupdateinstance',
            old_name='processes_bad_content',
            new_name='bad_content_errors_faced',
        ),
        migrations.RenameField(
            model_name='websiteupdateinstance',
            old_name='chapter_links_present',
            new_name='chapter_links_found',
        ),
        migrations.RenameField(
            model_name='websiteupdateinstance',
            old_name='processes_error',
            new_name='critical_errors_faced',
        ),
        migrations.RenameField(
            model_name='websiteupdateinstance',
            old_name='novel_links_present',
            new_name='novel_links_found',
        ),
        migrations.RenameField(
            model_name='websiteupdateinstance',
            old_name='processes_idle',
            new_name='novels_updated',
        ),
        migrations.RemoveField(
            model_name='websiteupdateinstance',
            name='processes_complete',
        ),
        migrations.RemoveField(
            model_name='websiteupdateinstance',
            name='processes_in_progress',
        ),
        migrations.AddField(
            model_name='websiteupdateinstance',
            name='novels_update_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='websiteupdateinstance',
            name='novels_updated_per_min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='websiteupdateinstance',
            name='scraper_errors_faced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='websiteupdateinstance',
            name='sum_novel_process_times',
            field=models.IntegerField(default=0),
        ),
    ]
