# Generated by Django 5.1.1 on 2024-09-12 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NovelLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=8096)),
                ('initialized', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('link', models.CharField(max_length=8096)),
                ('crawler_start_link', models.CharField(max_length=8096)),
                ('directory', models.CharField(blank=True, max_length=8096, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChapterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=8096)),
                ('initialized', models.BooleanField(default=False)),
                ('novel_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_links', to='links_manager.novellink')),
            ],
        ),
        migrations.AddField(
            model_name='novellink',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novel_links', to='links_manager.website'),
        ),
    ]
