# Generated by Django 5.1.1 on 2024-09-18 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novels_storage', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=8096)),
                ('name', models.CharField(max_length=1024)),
                ('novel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link', to='novels_storage.novel')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=8096)),
                ('name', models.CharField(max_length=1024)),
                ('novel_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_links', to='links_manager.novellink')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_link', models.CharField(max_length=8096)),
                ('crawler_start_link', models.CharField(max_length=8096)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link_object', to='novels_storage.website')),
            ],
        ),
        migrations.AddField(
            model_name='novellink',
            name='website_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novel_links', to='links_manager.websitelink'),
        ),
    ]
