# Generated by Django 5.1.1 on 2024-09-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='directory',
            new_name='chapter_link_pages_directory',
        ),
        migrations.AddField(
            model_name='website',
            name='novel_link_pages_directory',
            field=models.CharField(blank=True, max_length=8096, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='website_directory',
            field=models.CharField(blank=True, max_length=8096, null=True),
        ),
    ]
