# Generated by Django 5.1.1 on 2024-09-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_manager', '0002_rename_directory_website_chapter_link_pages_directory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='chapter_link_pages_directory',
        ),
        migrations.AddField(
            model_name='website',
            name='novels_directory',
            field=models.CharField(blank=True, max_length=8096, null=True),
        ),
    ]
