# Generated by Django 5.1.1 on 2024-09-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_manager', '0003_remove_website_chapter_link_pages_directory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='novel_pages_directory',
            field=models.CharField(blank=True, max_length=8096, null=True),
        ),
    ]
