# Generated by Django 5.1.1 on 2024-09-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_manager', '0004_website_novel_pages_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='novellink',
            name='chapter_link_pages_directory',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='novellink',
            name='chapter_pages_directory',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='novellink',
            name='novel_directory',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='novellink',
            name='slug_name',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='website',
            name='novel_pages_directory',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='novels_directory',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='website_directory',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
