# Generated by Django 5.1.1 on 2024-09-13 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links_manager', '0005_novellink_chapter_link_pages_directory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='novel_pages_directory',
        ),
    ]
