# Generated by Django 5.1.1 on 2024-09-15 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_manager', '0006_remove_website_novel_pages_directory'),
        ('novels_storage', '0006_website_remove_chapter_link_remove_novel_link_and_more'),
        ('spiders_manager', '0009_remove_websiteupdateinstance_update_cycle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novellink',
            name='website',
        ),
        migrations.RemoveField(
            model_name='chapterlink',
            name='initialized',
        ),
        migrations.RemoveField(
            model_name='novellink',
            name='chapter_link_pages_directory',
        ),
        migrations.RemoveField(
            model_name='novellink',
            name='chapter_pages_directory',
        ),
        migrations.RemoveField(
            model_name='novellink',
            name='initialized',
        ),
        migrations.RemoveField(
            model_name='novellink',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='novellink',
            name='novel_directory',
        ),
        migrations.RemoveField(
            model_name='novellink',
            name='slug_name',
        ),
        migrations.AddField(
            model_name='chapterlink',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='novels_storage.chapter'),
        ),
        migrations.AddField(
            model_name='chapterlink',
            name='name',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novellink',
            name='name',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novellink',
            name='novel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='novels_storage.novel'),
        ),
        migrations.CreateModel(
            name='WebsiteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_link', models.CharField(max_length=8096)),
                ('crawler_start_link', models.CharField(max_length=8096)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link_object', to='novels_storage.website')),
            ],
        ),
        migrations.AddField(
            model_name='novellink',
            name='website_link',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='novel_links', to='links_manager.websitelink'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Website',
        ),
    ]
