# Generated by Django 5.1.1 on 2024-09-16 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links_manager', '0007_remove_novellink_website_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterlink',
            name='chapter',
        ),
    ]
