# Generated by Django 5.1.1 on 2024-09-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_manager', '0008_remove_chapterlink_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='novellink',
            name='selected_for_update',
            field=models.BooleanField(default=False),
        ),
    ]
