# Generated by Django 5.1.1 on 2024-09-18 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_manager', '0009_novellink_selected_for_update'),
        ('novels_storage', '0007_novel_initialized_novel_is_being_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novellink',
            name='selected_for_update',
        ),
        migrations.AlterField(
            model_name='novellink',
            name='novel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='novels_storage.novel'),
        ),
    ]
